name: ViralClip
options:
  bundleIdPrefix: com.viralclip
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  ViralClip:
    type: application
    platform: iOS
    sources:
      - path: ViralClip
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "ViralClip needs access to your photos and videos to create amazing content for you."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "ViralClip needs to save generated videos to your library."
        INFOPLIST_KEY_NSCameraUsageDescription: "ViralClip can use your camera to capture new content."
        PRODUCT_BUNDLE_IDENTIFIER: com.viralclip.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED: NO
        DEVELOPMENT_TEAM: ""
